sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge Group-F
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network Group-F mongo
  - docker build -t Group-F .
  - docker run --network Group-F Group-F